# Generated by Django 4.1 on 2022-12-05 02:34

import django.db.models.deletion
from django.db import migrations, models

import coreplus.utils.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coreplus_contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coreplus_contacts.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='loc_name',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('office', 'Office'), ('branch_office', 'Branch Office'), ('billing', 'Billing'), ('shipping', 'Shipping'), ('drop_shipping', 'Dropshipping'), ('deliverable', 'Deliverable'), ('else', 'Else')], default='billing', help_text='E.g. Shipping or billing', max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='postcode',
            field=coreplus.utils.models.fields.UppercaseCharField(blank=True, max_length=64, null=True, verbose_name='Post/Zip-code'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='province'),
        ),
        migrations.AlterField(
            model_name='deliverableaddress',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='deliverableaddress',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='deliverableaddress',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coreplus_contacts.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='deliverableaddress',
            name='loc_name',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('office', 'Office'), ('branch_office', 'Branch Office'), ('billing', 'Billing'), ('shipping', 'Shipping'), ('drop_shipping', 'Dropshipping'), ('deliverable', 'Deliverable'), ('else', 'Else')], default='billing', help_text='E.g. Shipping or billing', max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='deliverableaddress',
            name='postcode',
            field=coreplus.utils.models.fields.UppercaseCharField(blank=True, max_length=64, null=True, verbose_name='Post/Zip-code'),
        ),
        migrations.AlterField(
            model_name='deliverableaddress',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='province'),
        ),
        migrations.AlterField(
            model_name='linkedaddress',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='linkedaddress',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='linkedaddress',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coreplus_contacts.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='linkedaddress',
            name='postcode',
            field=coreplus.utils.models.fields.UppercaseCharField(blank=True, max_length=64, null=True, verbose_name='Post/Zip-code'),
        ),
        migrations.AlterField(
            model_name='linkedaddress',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='province'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coreplus_contacts.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='loc_name',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('office', 'Office'), ('branch_office', 'Branch Office'), ('billing', 'Billing'), ('shipping', 'Shipping'), ('drop_shipping', 'Dropshipping'), ('deliverable', 'Deliverable'), ('else', 'Else')], default='billing', help_text='E.g. Shipping or billing', max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='postcode',
            field=coreplus.utils.models.fields.UppercaseCharField(blank=True, max_length=64, null=True, verbose_name='Post/Zip-code'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='province'),
        ),
    ]
