# Generated by Django 4.0.7 on 2023-02-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreplus_contacts', '0002_alter_billingaddress_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='district'),
        ),
        migrations.AddField(
            model_name='deliverableaddress',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='district'),
        ),
        migrations.AddField(
            model_name='linkedaddress',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='district'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='district'),
        ),
    ]
