# Generated by Django 4.1 on 2023-01-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coreplus_discuss", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discuss",
            name="flag",
            field=models.JSONField(
                blank=True,
                editable=False,
                help_text='JSON fields contains {"spam": 1, "hoax":2, "bullying":3}',
                null=True,
                verbose_name="flag",
            ),
        ),
    ]
